### ISSUE TITLE
Possible error on Container-OptimizedOS.puml?

### ISSUE THREAD

**Issue by GeoffMurray-chc** [gamma-data/GCP-C4-PlantUML#1]
First of all, thank you for all your efforts on this set. My team were just saying "wouldn't it be nice" this am, and found this library. 

A question on this particular file. 

It doesn't seem to have the same pattern as others. Most have two sprite definitions:

SpriteName
SpriteNameParticipant

Different sizes, etc. 

This file just has two sprite definitions with the same name:

SpriteName
SpriteName

I added Participant to the name of the second sprite, and it seemed to behave more as i would have expected for the other elements defined. 

The original contents are as follows. 
....
sprite $Container [70x70/4z] {
xTS5RaOn30DWs_U_ytZpe5vIoSBDeWVfr_I71rZcFzGKpD4c5KGSbrDeHjjK4B6Yg8BaPgYRv5OA32kARbD1n8gY4r9eXaCPLyqiPfePRXQDgIWsGdedC3FY
8x7GEP_JrnDd9Y0UO2KpReO1-Que5MTUxueBfD1uFAmtnTtQNody60OdDZCV11mVuc5Q1kKRmz_drVTuEjgH14Q59yNTK-AR0NWt92d0jv_MMd6T5sC1HuL3
Bm3bmKd1bI85XIU5TmhphouhQTxysxMI1mp_8-b3kVXJ7qe1QlvFv-kBBqjUGgnEEgsjhdNvpCrrDv_YZ0WEpmpdg-juRpH4tjnYx-_JbMS63lE4w-xKBtKV
bfxh2isKddSR31eAqM2Gma8hhNSri8407GK5PBqcei1WpEmGVo2F
}

sprite $Container [50x50/4z] {
pPO53aCn34DZt__EuvLSJ_8um-JhXOhr_q8Zi82N623VGv0XmhSJZ04Y9YX05WJw66hp8U0ykH0-tRqPtGK4SG1hr7RvhW07ou9eYAjw-NW4SuYBcTqLbD0G
77keGQXgBz0GcbHBjw1UiKqA3IiXQCguZv_E2LluzRiP3G4XjjrHpSUmAYw4wQvCgnQiOCPy5sHiZyvKjQ0AZ-TkmKQ50C-jGM_sJ_nUGbfVyNvL2FR4PDyD
W-JdHtwgnSJdJsUywSxWMrpVbYC
}

....

**Comment by GeoffMurray-chc** [comment]
Actually, with a little more playing around, I found what I think are maybe a couple of problems. I found that the "-" seemed to be causing a problem, and the sprite naming wasn't matching what was in the definitions at the end of this file, and so I made them match like the attached file, and now I can use them properly in the diagrams. 

``sprite $ContainerOptimizedOS [70x70/4z] {
xTS5RaOn30DWs_U_ytZpe5vIoSBDeWVfr_I71rZcFzGKpD4c5KGSbrDeHjjK4B6Yg8BaPgYRv5OA32kARbD1n8gY4r9eXaCPLyqiPfePRXQDgIWsGdedC3FY
8x7GEP_JrnDd9Y0UO2KpReO1-Que5MTUxueBfD1uFAmtnTtQNody60OdDZCV11mVuc5Q1kKRmz_drVTuEjgH14Q59yNTK-AR0NWt92d0jv_MMd6T5sC1HuL3
Bm3bmKd1bI85XIU5TmhphouhQTxysxMI1mp_8-b3kVXJ7qe1QlvFv-kBBqjUGgnEEgsjhdNvpCrrDv_YZ0WEpmpdg-juRpH4tjnYx-_JbMS63lE4w-xKBtKV
bfxh2isKddSR31eAqM2Gma8hhNSri8407GK5PBqcei1WpEmGVo2F
}

sprite $ContainerOptimizedOSParticipant [50x50/4z] {
pPO53aCn34DZt__EuvLSJ_8um-JhXOhr_q8Zi82N623VGv0XmhSJZ04Y9YX05WJw66hp8U0ykH0-tRqPtGK4SG1hr7RvhW07ou9eYAjw-NW4SuYBcTqLbD0G
77keGQXgBz0GcbHBjw1UiKqA3IiXQCguZv_E2LluzRiP3G4XjjrHpSUmAYw4wQvCgnQiOCPy5sHiZyvKjQ0AZ-TkmKQ50C-jGM_sJ_nUGbfVyNvL2FR4PDyD
W-JdHtwgnSJdJsUywSxWMrpVbYC
}


GCPEntityColoring(ContainerOptimizedOS)
!define ContainerOptimizedOS(e_alias, e_label, e_techn) GCPEntity(e_alias, e_label, e_techn, GCP_SYMBOL_COLOR, ContainerOptimizedOS, ContainerOptimizedOS)
!define ContainerOptimizedOS(e_alias, e_label, e_techn, e_descr) GCPEntity(e_alias, e_label, e_techn, e_descr, GCP_SYMBOL_COLOR, ContainerOptimizedOS, ContainerOptimizedOS)
!define ContainerOptimizedOSParticipant(p_alias, p_label, p_techn) GCPParticipant(p_alias, p_label, p_techn, GCP_SYMBOL_COLOR, ContainerOptimizedOSParticipant, ContainerOptimizedOSParticipant)
!define ContainerOptimizedOSParticipant(p_alias, p_label, p_techn, p_descr) GCPParticipant(p_alias, p_label, p_techn, p_descr, GCP_SYMBOL_COLOR, ContainerOptimizedOSParticipant, Container-OptimizedOSParticipant)
"
I'm guessing the file should be renamed if you decide to remove the "-".

**Comment by jeffreyaven** [comment]
Thanks Geoff, did you want to raise a PR for this and I can merge

**Comment by GeoffMurray-chc** [comment]
Ok - will try :-). My first one :-).

**Comment by jeffreyaven** [comment]
OK I can help you with this

**Comment by GeoffMurray-chc** [comment]
I cloned it to my desktop, I tried to create a branch and push, but not allowed. Do I do a PR straight into master from my local desktop?

**Comment by jeffreyaven** [comment]
you should be able to clone locally, create a feature branch using `git checkout -b mybranch` then `git add`, `git commit`  and `git push` pushing from origin to your feature branch creating this on GitHub, then raise a PR from the web UI

**Comment by GeoffMurray-chc** [comment]
Hmm. I think I did it correctly, but got this error message: 

fatal: unable to access 'https://github.com/gamma-data/GCP-C4-PlantUML/': The requested URL returned error: 403

**Comment by jeffreyaven** [comment]
try again now Geoff

**Comment by GeoffMurray-chc** [comment]
Hmm. Still can't quite see what I'm doing wrong:

git push origin ContainerFix

remote: Permission to gamma-data/GCP-C4-PlantUML.git denied to GeoffMurray-chc.
fatal: unable to access 'https://github.com/gamma-data/GCP-C4-PlantUML/': The requested URL returned error: 403

**Comment by TomKlimovski** [comment]
Hi @GeoffMurray-chc , have you set up 2FA on your github account?

**Comment by GeoffMurray-chc** [comment]
I did not set up 2FA - is that required? Apologies - very novice here.

**Comment by TomKlimovski** [comment]
No, not required, but can sometimes interfere with git-push. 
Most of the time on a 403 it's because you haven't set up your creds so it doesn't know who you are, or you have to include your username in the github url 
Here's a starting point: https://www.a2hosting.com/kb/developer-corner/version-control-systems1/403-forbidden-error-message-when-you-try-to-push-to-a-github-repository#:~:text=There%20are%20a%20few%20possible,HTTPS%20URL%20to%20work%20correctly.

Also make sure you're creating a new branch from master, and committing your changes to your own branch.

**Comment by jeffreyaven** [comment]
@GeoffMurray-chc if this gets too hard, maybe just send me the file name you are modifying and the updated content, you can put this in the issue, I will then sort it out

**Comment by GeoffMurray-chc** [comment]
I think there must be something wrong with my setup. I will need to do the debugging, but getting close to crashing (still have to do what I actually intended to do today :-) ). 

I renamed the file named: templates\Compute\Container-OptimizedOS.puml to templates\Compute\ContainerOptimizedOS.puml and then put in the contents that I placed in this post: https://github.com/gamma-data/GCP-C4-PlantUML/issues/1#issuecomment-713314965 (without the quotes beginning and ending how I had to copy it into that post, of course. 

Sorry - just can't get my credentials working for some reason.

**Comment by jeffreyaven** [comment]
Hi Geoff, I am going to fix this properly, the templates and sprites are generated using `scripts/encode-sprites.ps1` - this way when GCP adds new services you can dynamically regenerate templates, Ill make the changes here and regenerate the templates, should have this done tomorrow.

**Comment by GeoffMurray-chc** [comment]
No worries. If the file name stays with a dash, it might work, not sure. Thanks for looking into it.

**Comment by jeffreyaven** [comment]
Hi @GeoffMurray-chc please pull or clone the repo and test again, should be all good!  let me know how you go

**Comment by GeoffMurray-chc** [comment]
Will do. Just in a few back to back meetings. Will try within a few hours.

**Comment by GeoffMurray-chc** [comment]
I managed to squeeze in a test. Looks great, thank you for your help.
