### ISSUE TITLE
Firebase images not working

### ISSUE THREAD

**Issue by NJ-Brad** [gamma-data/GCP-C4-PlantUML#5]
Some of the images in the Firebase folder do not show up.

Affected Images:
CloudFirestore
CloudFunctions
CloudStorage
FirebaseAuthentication
FirebaseExtensions
FirebaseHosting
FirebaseMachineLearning
FirebaseRealtimeDatabase

The encoded image is very short.

As I was experimenting with this I noticed that the higher color depth images were working, but the /4 images were not.
The color used seems to be too close to white. When I changed the background to a darker color, I was able to generate the images locally.

I'm not sure what color should be used instead, or I would put in a pull-request myself.

**Comment by jeffreyaven** [comment]
Hi @NJ-Brad thanks for raising this, please raise a PR and I can review and merge

**Comment by NJ-Brad** [comment]
What color would you suggest for the background?

**Comment by jeffreyaven** [comment]
I would go with the orange used in most of the native Firebase images (#FF8A65)

**Comment by NJ-Brad** [comment]
Changes have been merged and tested.  Closing issue.
